name: Inference

on: 
  pull_request:
    branches:
    - main

jobs:
  inference:
    runs-on: ubuntu-latest
    steps:
    - name: one
      env: 
        VARIABLE: "hello"
      run: export VARIABLE=$RANDOM 

    - name: two
      uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: ${{ VARIABLE }}
